{{- /* -------------------------------------------------
   Read from the ska-mid-cbf-fhs-vcc values.yaml.
   Since the vccchart name contains hyphens, must save it
   to a var and use the `index` function to fetch it.
   ------------------------------------------------- */ -}}
{{- $vcc := index .Values "ska-mid-cbf-fhs-vcc" | default dict -}}
{{- if $vcc.global.bar.secret.vault.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "fhs-bar-secret-name" . }}
spec:
  type: kv-v2
  mount: {{ $vcc.global.bar.secret.vault.mount }}
  path:  {{ $vcc.global.bar.secret.vault.secretPath }}
  destination:
    name: {{ include "fhs-bar-secret-name" . }}
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      includes:
      {{- range $vcc.global.bar.secret.vault.secretKeys }}
        - {{ . }}
      {{- end }}
{{- else }}
{{- /* -------------------------------------------------
When Vault is disabled (Minikube) we deliberately emit **no** object.
The secret will already exist because `make k8s-create-bar-secret` creates it.
   ------------------------------------------------- */ -}}
{{- end }}