# GitLab CI in conjunction with GitLab Runner can use Docker Engine to test and build any application.
# Docker, when used with GitLab CI, runs each job in a separate and isolated container using the predefined image that is set up in .gitlab-ci.yml.
# In this case we use the latest python docker image to build and test this project.
default:
  image: $SKA_PYTHON_PYTANGO_BUILDER_IMAGE

# cache is used to specify a list of files and directories which should be cached between jobs. You can only use paths that are within the project workspace.
# If cache is defined outside the scope of jobs, it means it is set globally and all jobs will use that definition
# cache:
#   paths:

stages:
  - lint
  - build
  - test
  - pages
  - publish
  - scan



# Standardised included jobs
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MINIKUBE: "false"

# Include CI templates
include:

# Python
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python.gitlab-ci.yml'

# OCI images
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/oci-image.gitlab-ci.yml'

# Helm charts
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/helm-chart.gitlab-ci.yml'

# Docs
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'

# Docs
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/release.gitlab-ci.yml'

# .post step finalisers eg: badges
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

docs-build:
  rules:
    - when: never

python-test:
  before_script:
    - '[ -f .make/python.mk ] || (echo "File python.mk not included in Makefile; exit 1")'
    - 'make help | grep python-test'
    - poetry config virtualenvs.in-project true
    - echo "python-build Setting.. poetry config virtualenvs.create true"
    - poetry config virtualenvs.create true
    - |
      if [[ -f pyproject.toml ]]; then
        echo "python-test: Installing with poetry";
        poetry env use python3.12;
        time poetry install;
      else
        if  [[ -f requirements.txt ]]; then
          echo "python-test: Installing with pip";
          time pip3 install -r requirements.txt;
        fi;
      fi;

python-lint:
  before_script:
    - '[ -f .make/python.mk ] || (echo "File python.mk not included in Makefile"; exit 1;)'
    - 'make help | grep python-lint'
    - poetry config virtualenvs.in-project true
    - echo "python-build Setting.. poetry config virtualenvs.create true"
    - poetry config virtualenvs.create true
    - |
      if [[ -f pyproject.toml ]]; then
        if [[ -n $CI_POETRY_VERSION ]]; then
          # Check installed Poetry version
          CURRENT_POETRY_VERSION=$(poetry --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "python-lint: Installed Poetry version: $CURRENT_POETRY_VERSION, Required: $CI_POETRY_VERSION"
          # Compare versions
          if [[ $(printf '%s\n' "$CURRENT_POETRY_VERSION" "$CI_POETRY_VERSION" | sort -V | head -n1) != "$CI_POETRY_VERSION" ]]; then
            echo "python-lint: Updating poetry to $CI_POETRY_VERSION";
            pipx uninstall poetry && pipx install poetry==$CI_POETRY_VERSION;
          fi;
        fi;

        echo "python-lint: Installing with poetry";
        poetry env use python3.12;
        time poetry install --all-extras;
      else
        if  [[ -f requirements.txt ]]; then
          echo "python-lint: Installing with pip";
          time pip3 install -r requirements.txt;
        fi;
      fi;

python-build-for-development:
  variables:
    PYTHON_RUNNER: "poetry run "

python-build-for-publication:
  variables:
    PYTHON_RUNNER: "poetry run "
