# GitLab CI in conjunction with GitLab Runner can use Docker Engine to test and build any application.
# Docker, when used with GitLab CI, runs each job in a separate and isolated container using the predefined image that is set up in .gitlab-ci.yml.
# In this case we use the latest python docker image to build and test this project.
default:
  image: $SKA_PYTHON_PYTANGO_BUILDER_IMAGE

# cache is used to specify a list of files and directories which should be cached between jobs. You can only use paths that are within the project workspace.
# If cache is defined outside the scope of jobs, it means it is set globally and all jobs will use that definition
# cache:
#   paths:

stages:
  - ci-init
  - lint
  - build
  - test
  - pages
  - publish
  - scan



# Standardised included jobs
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MINIKUBE: "false"
  CI_POETRY_VERSION: "2.4.0"
  BASE_IMAGE_URL: registry.gitlab.com/ska-telescope/ska-mid-cbf/monitor-control/ska-mid-cbf-fhs-vcc/ska-mid-cbf-fhs-vcc-ci-base
  DOCS_PYTHON_RUNNER: "poetry run python -m "
  DOCS_SPHINXBUILD: "poetry run python -m sphinx "

get-version:
  image: $SKA_K8S_TOOLS_BUILD_DEPLOY
  stage: ci-init
  tags:
    - ${SKA_DEFAULT_RUNNER}
  script:
    - REL_VERSION=$(awk -F= '/^release=/{print $2}' .release)
    - DEV_VERSION="$REL_VERSION"-dev.c"$CI_COMMIT_SHORT_SHA"
    - BASE_IMAGE="$BASE_IMAGE_URL":"$DEV_VERSION"
    - echo "REL_VERSION=$REL_VERSION" >> build.env
    - echo "DEV_VERSION=$DEV_VERSION" >> build.env
    - echo "BASE_IMAGE=$BASE_IMAGE" >> build.env
  artifacts:
    reports:
      dotenv: build.env

ci-base-image-build:
  image: $SKA_K8S_TOOLS_BUILD_DEPLOY
  stage: ci-init
  tags:
    - ${SKA_DEFAULT_RUNNER}
  before_script:
    - '[ -f .make/oci.mk ] || (echo "File oci.mk not included in Makefile; exit 1")'
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - mkdir -p build
  script:
    - make oci-build CAR_OCI_REGISTRY_HOST=${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME} OCI_IMAGE=ska-mid-cbf-fhs-vcc-ci-base OCI_IMAGE_FILE_PATH=./ci.Dockerfile OCI_BUILD_ADDITIONAL_ARGS="--build-arg ci_poetry_version=$CI_POETRY_VERSION"
  artifacts:
    paths:
      - build/

# Include CI templates
include:

# Python
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python.gitlab-ci.yml'

# OCI images
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/oci-image.gitlab-ci.yml'

# Helm charts
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/helm-chart.gitlab-ci.yml'

# Docs
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'

# Docs
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/release.gitlab-ci.yml'

# .post step finalisers eg: badges
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

docs-build:
  rules:
    - when: never

python-test:
  before_script:
    - '[ -f .make/python.mk ] || (echo "File python.mk not included in Makefile; exit 1")'
    - 'make help | grep python-test'
    - poetry config virtualenvs.in-project true
    - echo "python-build Setting.. poetry config virtualenvs.create true"
    - poetry config virtualenvs.create true
    - |
      if [[ -f pyproject.toml ]]; then
        echo "python-test: Installing with poetry";
        poetry env use python3.12;
        time poetry install;
      else
        if  [[ -f requirements.txt ]]; then
          echo "python-test: Installing with pip";
          time pip3 install -r requirements.txt;
        fi;
      fi;

python-lint:
  image: "$BASE_IMAGE"
  variables:
    PYTHON_RUNNER: "poetry run python -m "
  needs:
    - ci-base-image-build
    - get-version
  before_script:
    - cd /ska-mid-cbf-fhs-fsp
  after_script:
    - cp -r /ska-mid-cbf-fhs-vcc/build/ /builds/ska-telescope/ska-mid-cbf/monitor-control/ska-mid-cbf-fhs-vcc

python-build-for-development:
  image: "$BASE_IMAGE"
  variables:
    PYTHON_RUNNER: "poetry run "
  needs:
    - python-lint
    - get-version
  before_script:
    - cd /ska-mid-cbf-fhs-vcc
    - cat pyproject.toml
    - poetry install --only ci
  script:
    - make python-build PYTHON_BUILD_TYPE="non_tag_pyproject"
    - cp -r /ska-mid-cbf-fhs-vcc/dist/ /builds/ska-telescope/ska-mid-cbf/monitor-control/ska-mid-cbf-fhs-vcc

python-build-for-publication:
  image: "$BASE_IMAGE"
  variables:
    PYTHON_RUNNER: "poetry run "
  needs:
    - python-lint
    - get-version
  before_script:
    - cd /ska-mid-cbf-fhs-vcc
    - poetry install --only ci
  script:
    - make python-build PYTHON_BUILD_TYPE="tag_pyproject"
    - cp -r /ska-mid-cbf-fhs-vcc/dist/ /builds/ska-telescope/ska-mid-cbf/monitor-control/ska-mid-cbf-fhs-vcc

python-publish-to-gitlab:
  needs:
    - job: python-build-for-development
      optional: true
    - job: python-build-for-publication
      optional: true

python-publish-to-car:
  needs:
    - python-test
    - python-build-for-publication
