apiVersion: v2
name: ska-mid-cbf-umbrella
description: An umbrella Helm chart for deploying the whole Mid_CBF FHS-VCC prototype.
appVersion: 0.2.0
version: 0.2.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: ska-tango-util
  version: 0.4.20
  repository: https://artefact.skao.int/repository/helm-internal
  #repository: "file:///home/ja004983_p/projects/ska-tango-charts/charts/ska-tango-util"
  #repository: "file://../../../ska-tango-charts/charts/ska-tango-util"
- name: ska-tango-base
  version: 0.4.20
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-taranta
  version: 1.0.29
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-taranta.enabled
- name: ska-taranta-auth
  version: 0.1.5
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-taranta-auth.enabled
- name: ska-mid-cbf-fhs-vcc
  version: 0.2.0
  repository: "file://../ska-mid-cbf-fhs-vcc"
- name: ska-mid-cbf-fhs-vcc-boogie
  version: 0.2.1
  repository: "file://../ska-mid-cbf-fhs-vcc-boogie"