display: ":0"
xauthority: "~/.Xauthority"

global:
  minikube: false
  tango_host: databaseds-tango-base-test:10000
  environment_variables: []
  operator: true
  labels:
    app: ska-mid-cbf-fhs-vcc
  sub-system:
    ska-tango-base:
      enabled: false

ska-tango-base:
  vnc:
    enabled: false
  tangorest:
    enabled: false
  ingress:
    enabled: false
  tangodb:
    use_pv: false

ska-taranta:
  enabled: false

ska-taranta-auth:
  enabled: false

ska-dashboard-repo:
  enabled: false
