display: ":0"
xauthority: "~/.Xauthority"

global:
  minikube: false
  tango_host: &tango_host tango-databaseds-test:10000
  environment_variables: []
  operator: true
  labels:
    app: ska-mid-cbf-fhs-vcc
  sub-system:
    ska-tango-base:
      enabled: false
  bar:
    url: "https://binary.artefact.skao.int/api/v3/repositories/raw-artefacts/artefacts"
    secret:
      vault:
        mount: psi-mid
        secretPath: production/bar-api-token
        secretKeys:
          - "BAR_API_TOKEN"

bar:
  secret:
    vault:
      enabled: true

ska-tango-base:
  vnc:
    enabled: false
  tangorest:
    enabled: false
  ingress:
    enabled: false
  tangodb:
    use_pv: false

ska-mid-cbf-fhs-vcc-boogie:
  enabled: true
  boogie:
    tango_host: *tango_host
