@startuml fhs_vcc_end_scan
!pragma teoz true

title FHS-VCC: EndScan()

!$MCSLifeline = "#DDDDEE"
!$FHSVCCBackground = "#f0dbb7"
!$AllBands = "#ffe680"
!$AllBandsLifeline = "#ffe680"
!$LowLevelDSBackground = "#cbecec"
!$LowLevelDS = "#99e6ff"
!$LowLevelDSLifeline = "#99e6ff"

participant "Control Software (MCS)" as mcs

box "FHS-VCC" $FHSVCCBackground
participant "All Bands Controller" as allbands $AllBands
box "Low-Level Device Servers" $LowLevelDSBackground
participant "200Gb Ethernet" as eth_ds $LowLevelDS
participant "Packet Validation" as pv_ds $LowLevelDS
participant "WIB" as wib_ds $LowLevelDS
participant "Pre-VCC WPMs" as wpm_pre_ds $LowLevelDS
participant "WFS" as wfs_ds $LowLevelDS
participant "VCCs" as vcc_ds $LowLevelDS
participant "FSS" as fss_ds $LowLevelDS
participant "Post-VCC WPMs" as wpm_post_ds $LowLevelDS
participant "Packetizer" as packetizer_ds $LowLevelDS
end box
end box

mcs -> allbands ++ $AllBandsLifeline: EndScan()
allbands -> allbands: ObsState = STOPPING

allbands -> eth_ds ++ $LowLevelDSLifeline: Stop()
group Stop() (repeat for all LL devices)
eth_ds -> eth_ds: stop() the FW
end
allbands <-- eth_ds --: ResultCode.OK

allbands -> pv_ds ++ $LowLevelDSLifeline: Stop()
allbands <-- pv_ds --: ResultCode.OK

allbands -> wib_ds ++ $LowLevelDSLifeline: Stop()
allbands <-- wib_ds --: ResultCode.OK

allbands -> allbands: ObsState = READY
mcs <-- allbands --: ResultCode.OK

@enduml