@startuml fhs_vcc_go_to_idle
!pragma teoz true

title FHS-VCC: GoToIdle()

!$MCSLifeline = "#DDDDEE"
!$FHSVCCBackground = "#f0dbb7"
!$AllBands = "#ffe680"
!$AllBandsLifeline = "#ffe680"
!$LowLevelDSBackground = "#cbecec"
!$LowLevelDS = "#99e6ff"
!$LowLevelDSLifeline = "#99e6ff"

participant "Control Software (MCS)" as mcs

box "FHS-VCC" $FHSVCCBackground
participant "All Bands Controller" as allbands $AllBands
box "Low-Level Device Servers" $LowLevelDSBackground
participant "200Gb Ethernet" as eth_ds $LowLevelDS
participant "Packet Validation" as pv_ds $LowLevelDS
participant "WIB" as wib_ds $LowLevelDS
participant "Pre-VCC WPMs" as wpm_pre_ds $LowLevelDS
participant "WFS" as wfs_ds $LowLevelDS
participant "VCCs" as vcc_ds $LowLevelDS
participant "FSS" as fss_ds $LowLevelDS
participant "Post-VCC WPMs" as wpm_post_ds $LowLevelDS
participant "VCC Stream Merge" as vccsm_ds $LowLevelDS
end box
end box

mcs -> allbands ++ $AllBandsLifeline: GoToIdle()
allbands -> allbands: Reset stored parameters

allbands -> eth_ds ++ $LowLevelDSLifeline: GoToIdle()
group GoToIdle() (repeat for all LL devices)
eth_ds -> eth_ds: deconfigure() the FW\nif it has configuration
end
allbands <-- eth_ds --: ResultCode.OK

allbands -> pv_ds ++ $LowLevelDSLifeline: GoToIdle()
allbands <-- pv_ds --: ResultCode.OK

allbands -> wib_ds ++ $LowLevelDSLifeline: GoToIdle()
allbands <-- wib_ds --: ResultCode.OK

allbands -> wpm_pre_ds ++ $LowLevelDSLifeline: GoToIdle()
allbands <-- wpm_pre_ds --: ResultCode.OK

allbands -> wfs_ds ++ $LowLevelDSLifeline: GoToIdle()
allbands <-- wfs_ds --: ResultCode.OK

allbands -> vcc_ds ++ $LowLevelDSLifeline: GoToIdle()
allbands <-- vcc_ds --: ResultCode.OK

allbands -> fss_ds ++ $LowLevelDSLifeline: GoToIdle()
allbands <-- fss_ds --: ResultCode.OK

allbands -> wpm_post_ds ++ $LowLevelDSLifeline: GoToIdle()
allbands <-- wpm_post_ds --: ResultCode.OK

allbands -> vccsm_ds ++ $LowLevelDSLifeline: GoToIdle()
allbands <-- vccsm_ds --: ResultCode.OK

allbands -> allbands: ObsState = IDLE
mcs <-- allbands --: ResultCode.OK

@enduml