@startuml vcc-all-bands-controller-states

' !theme crt-green

<style>
stateDiagram {
  element {
    BackGroundColor: #fdfca2;
  }

  arrow {
    LineColor: #Black;
    FontColor: #Black;
  }
}
</style>

title VCC All Bands Controller States

state NOT_CONFIGURED
state CONFIGURING
state CONFIGURED

[*]             -->         NOT_CONFIGURED
NOT_CONFIGURED  -->         CONFIGURING : ConfigureScan()

CONFIGURING     -->         CONFIGURED : ConfigureScan()\nsuccessful
CONFIGURING     -->         NOT_CONFIGURED : Abort()

CONFIGURED      -->         NOT_CONFIGURED : GoToIdle()
CONFIGURED      -->         NOT_CONFIGURED : Abort()

@enduml