@startuml vcc-all-bands-controller-simplified-states

' !theme crt-green

<style>
stateDiagram {
  element {
    BackGroundColor: #fdfca2;
  }

  arrow {
    LineColor: #Black;
    FontColor: #Black;
  }
}
</style>

title VCC All Bands Controller Observing States (Simplified)

state IDLE: Not configured
state READY: Configured

[*]           -->         IDLE
IDLE          -->         READY : ConfigureScan()

READY         -->         IDLE : GoToIdle()
READY         -->         IDLE : Abort()

@enduml