@startuml vcc-all-bands-controller-alt-2

' !theme crt-green

<style>
stateDiagram {
  element {
    BackGroundColor: #fdfca2;
  }

  arrow {
    LineColor: #Black;
    FontColor: #Black;
  }
}
</style>

title VCC All Bands Controller States

state NOT_CONFIGURED
state CONFIGURED

[*]             -->         NOT_CONFIGURED
NOT_CONFIGURED  -->         CONFIGURED : ConfigureScan()

CONFIGURED      -->         NOT_CONFIGURED : GoToIdle()
CONFIGURED      -->         NOT_CONFIGURED : Abort()

@enduml