
{{- if .Values.bar.secret.enabled }}

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "fhs-bar-secret-name" . }}
spec:
  type: kv-v2
  mount: {{ .Values.global.bar.secret.vault.mount }}
  path: {{ .Values.global.bar.secret.vault.secretPath }}
  destination:
    name: {{ include "fhs-bar-secret-name" . }}
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      includes:
      {{- range .Values.global.bar.secret.vault.secretKeys }}
        - {{ . }}
      {{- end }}

{{- end }}