{{- /*
   Render a VaultStaticSecret only when:
   • the chart is asked to create it (bar.secret.create == true) AND
   • Vault integration is enabled (global.bar.secret.vault.enabled == true)
   The ska-mid-cbf-umbrella chart can disable creation by setting bar.secret.create=false.
*/ -}}
{{- if and .Values.bar.secret.create .Values.global.bar.secret.vault.enabled }}

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "fhs-bar-secret-name" . }}
spec:
  type: kv-v2
  mount: {{ .Values.global.bar.secret.vault.mount }}
  path: {{ .Values.global.bar.secret.vault.secretPath }}
  destination:
    name: {{ include "fhs-bar-secret-name" . }}
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      includes:
      {{- range .Values.global.bar.secret.vault.secretKeys }}
        - {{ . }}
      {{- end }}

{{- else }}
{{- /* When the create flag is false (umbrella overrides) don't create it. */ -}}
{{- end }}