apiVersion: batch/v1
kind: Job
metadata:
  name: bitstream-download-job
spec:
  template:
    spec:
      containers:
        - name: bitstream-download-job
          image: alpine:latest
          command: ["sh", "-c"]
          args:
            - |
              apk add --no-cache curl tar && \
              BITSTREAM_SUBPATH={{ .Values.lowLevel.bitstreamId }}/{{ .Values.lowLevel.firmwareVersion }} && \
              TARBALL="ska-mid-cbf-{{ .Values.lowLevel.bitstreamId }}-{{ .Values.lowLevel.firmwareVersion }}.tar.gz" && \
              if [ ! -d {{ .Values.lowLevel.bitstreamPath }}/$BITSTREAM_SUBPATH ]; then \
                curl -L -o /tmp/$TARBALL {{ if .Values.lowLevel.bitstream_url_override -}} {{ .Values.lowLevel.bitstream_url_override }} {{- else -}} https://artefact.skao.int/repository/raw-internal/$TARBALL {{- end }} && \
                mkdir -p {{ .Values.lowLevel.bitstreamPath }}/$BITSTREAM_SUBPATH && \
                tar xvzf /tmp/$TARBALL -C {{ .Values.lowLevel.bitstreamPath }}/$BITSTREAM_SUBPATH && \
                find {{ $.Values.bitstreamMountPath }} ; \
              fi
          volumeMounts:
            - name: bitstream-pv
              mountPath: {{ .Values.lowLevel.bitstreamPath }}
      restartPolicy: Never
      volumes:
        - name: bitstream-pv
          persistentVolumeClaim:
            claimName: fhs-vcc-bitstream-pv