{{- if .Values.bitstreamDownloadJob.enabled }}

{{- if .Values.bar.secret.vault.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ska-mid-cbf-fhs-vcc-bar-secret
spec:
  type: kv-v2
  mount: {{ .Values.bar.secret.vault.mount }}
  path: {{ .Values.bar.secret.vault.secretPath }}
  destination:
    name: ska-mid-cbf-fhs-vcc-bar-secret
    create: true
---
{{- end }}

apiVersion: batch/v1
kind: Job
metadata:
  name: fhs-vcc-bitstream-download-job
spec:
  template:
    spec:
      containers:
        - name: fhs-vcc-bitstream-download-job
          image: alpine:latest
          command: ["sh", "-ec"]
          args:
            - |
              apk add --no-cache curl tar
              {{ range $index, $bitstream := values $.Values.properties.bitstreams -}}
              {{- $gitlab_url := $bitstream.gitlab_bitstream_url_override }}
              BITSTREAM_ID={{ $bitstream.id }}
              BITSTREAM_VER={{ $bitstream.version }}
              BITSTREAM_SUBPATH=$BITSTREAM_ID/$BITSTREAM_VER
              PACKAGE="ska-mid-cbf-${BITSTREAM_ID}"
              TARBALL="${PACKAGE}-${BITSTREAM_VER}.tar.gz"
              BAR_URL="{{ $.Values.bar.url }}"
              TARGET_DIR="{{ $.Values.bitstreamMountPath }}/$BITSTREAM_SUBPATH"
              {{- if not $gitlab_url }}
              if [ -z "$BAR_API_TOKEN" ]; then
                echo "ERROR: BAR_API_TOKEN is a required environmental variable to download bitstream from BAR"
                exit 1
              fi
              download_url="${BAR_URL}/${PACKAGE}/versions/${BITSTREAM_VER}/assets/${TARBALL}?format=raw"
              echo "download_url = $download_url"
              {{- end}}
              if [ ! -d "$TARGET_DIR" ]; then
                echo "Downloading bitstream $BITSTREAM_SUBPATH"
                {{- if $gitlab_url }}
                  curl -f -L -o "/tmp/${TARBALL}" "{{ $gitlab_url }}"
                {{- else }}
                  curl -f -L -o "/tmp/${TARBALL}" -H "Authorization: Bearer ${BAR_API_TOKEN}" "${download_url}"
                {{- end }}
                if [ -f "/tmp/${TARBALL}" ]; then
                  mkdir -p "$TARGET_DIR"
                  tar xvzf "/tmp/${TARBALL}" -C "$TARGET_DIR" {{ if $gitlab_url -}} --strip-components=3 {{- end }}
                fi
              else
                echo "Bitstream $BITSTREAM_SUBPATH has already been downloaded (probably by another download job)."
              fi
              {{ end -}}
              find {{ $.Values.bitstreamMountPath }}
              tail -f /dev/null
          env:
            - name: BAR_URL
              value: {{ .Values.bar.url | quote }}
            - name: BAR_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "ska-mid-cbf-fhs-vcc-bar-secret" . }}
                  key: BAR_API_TOKEN
          volumeMounts:
            - name: bitstream-pv
              mountPath: {{ .Values.bitstreamMountPath }}
      restartPolicy: Never
      volumes:
        - name: bitstream-pv
          persistentVolumeClaim:
            claimName: fhs-bitstream-pv
{{- end }}