{{- if .Values.bitstreamDownloadJob.enabled }}

{{- if .Values.bar.secret.vault.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ska-mid-cbf-fhs-vcc-bar-secret
spec:
  type: kv-v2
  mount: {{ .Values.bar.secret.vault.mount }}
  path: {{ .Values.bar.secret.vault.secretPath }}
  destination:
    name: ska-mid-cbf-fhs-vcc-bar-secret
    create: true
---
{{- end }}

apiVersion: batch/v1
kind: Job
metadata:
  name: fhs-vcc-bitstream-download-job
spec:
  template:
    spec:
      containers:
        - name: fhs-vcc-bitstream-download-job
          image: alpine:latest
          command: ["sh", "-ec"]
          args:
            - |
              apk add --no-cache curl tar
              {{ range $index, $bitstream := values $.Values.properties.bitstreams -}}
              BITSTREAM_ID={{ $bitstream.id }}
              BITSTREAM_VER={{ $bitstream.version }}
              BITSTREAM_SUBPATH=$BITSTREAM_ID/$BITSTREAM_VER
              PACKAGE="ska-mid-cbf-${BITSTREAM_ID}"
              TARBALL="${PACKAGE}-${BITSTREAM_VER}.tar.gz"
              BAR_URL="{{ $.Values.bar.url }}"
              echo "BAR_URL=$BAR_URL"
              echo "BAR_API_TOKEN=$BAR_API_TOKEN"
              if [ -n "$BAR_API_TOKEN" ]; then
                download_url="${BAR_URL}/${PACKAGE}/versions/${BITSTREAM_VER}/assets/${TARBALL}?format=raw"
                echo "download_url = $download_url"
                curl -v -H "Authorization: Bearer ${BAR_API_TOKEN}" "${download_url}"
              fi
              if [ ! -d {{ $.Values.bitstreamMountPath }}/$BITSTREAM_SUBPATH ]; then
                echo "Downloading bitstream $BITSTREAM_SUBPATH"
                curl -f -L -o /tmp/$TARBALL {{ if $bitstream.gitlab_bitstream_url_override -}} {{ $bitstream.gitlab_bitstream_url_override }} {{- else -}} https://artefact.skao.int/repository/raw-internal/$TARBALL {{- end }} ||
                echo "Could not locate tarball: $TARBALL" ;
                if [ -f /tmp/$TARBALL ]; then
                  mkdir -p {{ $.Values.bitstreamMountPath }}/$BITSTREAM_SUBPATH
                  tar xvzf /tmp/$TARBALL -C {{ $.Values.bitstreamMountPath }}/$BITSTREAM_SUBPATH {{ if $bitstream.gitlab_bitstream_url_override -}} --strip-components=3 {{- end }} ;
                fi ;
              else \
                echo "Bitstream $BITSTREAM_SUBPATH has already been downloaded (probably by another download job)." ;
              fi
              {{ end -}}
              find {{ $.Values.bitstreamMountPath }}
              tail -f /dev/null
          env:
          - name: BAR_URL
            value: {{ .Values.bar.url | quote }}
          - name: BAR_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "ska-mid-cbf-fhs-vcc-bar-secret" . }}
                key: BAR_API_TOKEN
          volumeMounts:
            - name: bitstream-pv
              mountPath: {{ .Values.bitstreamMountPath }}
      restartPolicy: Never
      volumes:
        - name: bitstream-pv
          persistentVolumeClaim:
            claimName: fhs-bitstream-pv
{{- end }}
