{{- if .Values.bitstreamDownloadJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: fhs-vcc-bitstream-download-job
spec:
  template:
    spec:
      containers:
        - name: fhs-vcc-bitstream-download-job
          image: alpine:latest
          command: ["sh", "-c"]
          args:
            - |
              apk add --no-cache curl tar && \
              {{ range $index, $bitstream := values $.Values.properties.bitstreams -}}
              BITSTREAM_ID={{ $bitstream.id }} && \
              BITSTREAM_VER={{ $bitstream.version }} && \
              BITSTREAM_SUBPATH=$BITSTREAM_ID/$BITSTREAM_VER && \
              TARBALL="ska-mid-cbf-$BITSTREAM_ID-$BITSTREAM_VER.tar.gz" && \
              if [ ! -d {{ $.Values.bitstreamMountPath }}/$BITSTREAM_SUBPATH ]; then \
                echo "Downloading bitstream $BITSTREAM_SUBPATH" && \
                curl -f -L -o /tmp/$TARBALL {{ if $bitstream.gitlab_bitstream_url_override -}} {{ $bitstream.gitlab_bitstream_url_override }} {{- else -}} https://artefact.skao.int/repository/raw-internal/$TARBALL {{- end }} || \
                echo "Could not locate tarball: $TARBALL" ; \
                if [ -f /tmp/$TARBALL ]; then \
                  mkdir -p {{ $.Values.bitstreamMountPath }}/$BITSTREAM_SUBPATH && \
                  tar xvzf /tmp/$TARBALL -C {{ $.Values.bitstreamMountPath }}/$BITSTREAM_SUBPATH {{ if $bitstream.gitlab_bitstream_url_override -}} --strip-components=3 {{- end }} ; \
                fi ; \
              else \
                echo "Bitstream $BITSTREAM_SUBPATH has already been downloaded (probably by another download job)." ; \
              fi && \
              {{ end -}}
              find {{ $.Values.bitstreamMountPath }}
          volumeMounts:
            - name: bitstream-pv
              mountPath: {{ .Values.bitstreamMountPath }}
      restartPolicy: Never
      volumes:
        - name: bitstream-pv
          persistentVolumeClaim:
            claimName: fhs-bitstream-pv
{{- end }}
