{{- if .Values.selectedFhsVccUnit }}
  {{- $fhsVccDeployment := include "findByName" (list .Values.selectedFhsVccUnit .Values.VCCUnits) | fromYaml }}

  {{- $mergedContext := merge $ (dict "VCCUnits" (list $fhsVccDeployment)) }}

  {{ include "ska-mid-cbf-fhs-vcc.deviceservers.yaml" $mergedContext }}

{{- else }}

  {{ include "ska-mid-cbf-fhs-vcc.deviceservers.yaml" $ }}

{{- end}}